version: '3.3'

services:
    db:
        build: ./deployments/docker/mysql
        container_name: managedby_db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 3300:3306
        volumes: 
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./log/mysql:/var/log/mysql